bookmarks/urls.py
from django.urls import path, include
from django.urls import re_path

from bookmarks import views
from bookmarks.api.routes import router
from bookmarks.feeds import (
    AllBookmarksFeed,
    UnreadBookmarksFeed,
    SharedBookmarksFeed,
    PublicSharedBookmarksFeed,
)

app_name = "bookmarks"
urlpatterns = [
    # Root view handling redirection based on user authentication
    re_path(r"^$", views.root, name="root"),
    # Bookmarks
    path("bookmarks", views.bookmarks.index, name="index"),
    path("bookmarks/action", views.bookmarks.index_action, name="index.action"),
    path("bookmarks/archived", views.bookmarks.archived, name="archived"),
    path(
        "bookmarks/archived/action",
        views.bookmarks.archived_action,
        name="archived.action",
    ),
    path("bookmarks/shared", views.bookmarks.shared, name="shared"),
    path(
        "bookmarks/shared/action", views.bookmarks.shared_action, name="shared.action"
    ),
    path("bookmarks/new", views.bookmarks.new, name="new"),
    path("bookmarks/close", views.bookmarks.close, name="close"),
    path("bookmarks/<int:bookmark_id>/edit", views.bookmarks.edit, name="edit"),
    # Assets
    path(
        "assets/<int:asset_id>",
        views.assets.view,
        name="assets.view",
    ),
    path(
        "assets/<int:asset_id>/read",
        views.assets.read,
        name="assets.read",
    ),
    # Settings
    path("settings", views.settings.general, name="settings.index"),
    path("settings/general", views.settings.general, name="settings.general"),
    path("settings/update", views.settings.update, name="settings.update"),
    path(
        "settings/integrations",
        views.settings.integrations,
        name="settings.integrations",
    ),
    path("settings/import", views.settings.bookmark_import, name="settings.import"),
    path("settings/export", views.settings.bookmark_export, name="settings.export"),
    # Toasts
    path("toasts/acknowledge", views.toasts.acknowledge, name="toasts.acknowledge"),
    # API
    path("api/", include(router.urls), name="api"),
    # Feeds
    path("feeds/<str:feed_key>/all", AllBookmarksFeed(), name="feeds.all"),
    path("feeds/<str:feed_key>/unread", UnreadBookmarksFeed(), name="feeds.unread"),
    path("feeds/<str:feed_key>/shared", SharedBookmarksFeed(), name="feeds.shared"),
    path("feeds/shared", PublicSharedBookmarksFeed(), name="feeds.public_shared"),
    # Health check
    path("health", views.health, name="health"),
    # Manifest
    path("manifest.json", views.manifest, name="manifest"),
]

siteroot/urls.py
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import path, include

from bookmarks.admin import linkding_admin_site


class LinkdingLoginView(auth_views.LoginView):
    """
    Custom login view to lazily add additional context data
    Allows to override settings in tests
    """

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["allow_registration"] = settings.ALLOW_REGISTRATION
        context["enable_oidc"] = settings.LD_ENABLE_OIDC
        return context


urlpatterns = [
    path("admin/", linkding_admin_site.urls),
    path(
        "login/",
        LinkdingLoginView.as_view(redirect_authenticated_user=True),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "change-password/",
        auth_views.PasswordChangeView.as_view(),
        name="change_password",
    ),
    path(
        "password-change-done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("", include("bookmarks.urls")),
]

if settings.LD_ENABLE_OIDC:
    urlpatterns.append(path("oidc/", include("mozilla_django_oidc.urls")))

if settings.LD_CONTEXT_PATH:
    urlpatterns = [path(settings.LD_CONTEXT_PATH, include(urlpatterns))]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

if settings.ALLOW_REGISTRATION:
    urlpatterns.append(path("", include("django_registration.backends.one_step.urls")))

bookmarks/api/routes.py
import logging

from rest_framework import viewsets, mixins, status
from rest_framework.decorators import action
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.routers import DefaultRouter

from bookmarks import queries
from bookmarks.api.serializers import (
    BookmarkSerializer,
    TagSerializer,
    UserProfileSerializer,
)
from bookmarks.models import Bookmark, BookmarkSearch, Tag, User
from bookmarks.services import auto_tagging
from bookmarks.services.bookmarks import (
    archive_bookmark,
    unarchive_bookmark,
    website_loader,
)
from bookmarks.services.website_loader import WebsiteMetadata

logger = logging.getLogger(__name__)


class BookmarkViewSet(
    viewsets.GenericViewSet,
    mixins.ListModelMixin,
    mixins.RetrieveModelMixin,
    mixins.CreateModelMixin,
    mixins.UpdateModelMixin,
    mixins.DestroyModelMixin,
):
    serializer_class = BookmarkSerializer

    def get_permissions(self):
        # Allow unauthenticated access to shared bookmarks.
        # The shared action should still filter bookmarks so that
        # unauthenticated users only see bookmarks from users that have public
        # sharing explicitly enabled
        if self.action == "shared":
            return [AllowAny()]

        # Otherwise use default permissions which should require authentication
        return super().get_permissions()

    def get_queryset(self):
        user = self.request.user
        # For list action, use query set that applies search and tag projections
        if self.action == "list":
            search = BookmarkSearch.from_request(self.request.GET)
            return queries.query_bookmarks(user, user.profile, search)

        # For single entity actions use default query set without projections
        return Bookmark.objects.all().filter(owner=user)

    def get_serializer_context(self):
        return {"request": self.request, "user": self.request.user}

    @action(methods=["get"], detail=False)
    def archived(self, request):
        user = request.user
        search = BookmarkSearch.from_request(request.GET)
        query_set = queries.query_archived_bookmarks(user, user.profile, search)
        page = self.paginate_queryset(query_set)
        serializer = self.get_serializer(page, many=True)
        data = serializer.data
        return self.get_paginated_response(data)

    @action(methods=["get"], detail=False)
    def shared(self, request):
        search = BookmarkSearch.from_request(request.GET)
        user = User.objects.filter(username=search.user).first()
        public_only = not request.user.is_authenticated
        query_set = queries.query_shared_bookmarks(
            user, request.user_profile, search, public_only
        )
        page = self.paginate_queryset(query_set)
        serializer = self.get_serializer(page, many=True)
        data = serializer.data
        return self.get_paginated_response(data)

    @action(methods=["post"], detail=True)
    def archive(self, request, pk):
        bookmark = self.get_object()
        archive_bookmark(bookmark)
        return Response(status=status.HTTP_204_NO_CONTENT)

    @action(methods=["post"], detail=True)
    def unarchive(self, request, pk):
        bookmark = self.get_object()
        unarchive_bookmark(bookmark)
        return Response(status=status.HTTP_204_NO_CONTENT)

    @action(methods=["get"], detail=False)
    def check(self, request):
        url = request.GET.get("url")
        bookmark = Bookmark.objects.filter(owner=request.user, url=url).first()
        existing_bookmark_data = (
            self.get_serializer(bookmark).data if bookmark else None
        )

        # Either return metadata from existing bookmark, or scrape from URL
        if bookmark:
            metadata = WebsiteMetadata(
                url,
                bookmark.website_title,
                bookmark.website_description,
                None,
            )
        else:
            metadata = website_loader.load_website_metadata(url)

        # Return tags that would be automatically applied to the bookmark
        profile = request.user.profile
        auto_tags = []
        if profile.auto_tagging_rules:
            try:
                auto_tags = auto_tagging.get_tags(profile.auto_tagging_rules, url)
            except Exception as e:
                logger.error(
                    f"Failed to auto-tag bookmark. url={bookmark.url}",
                    exc_info=e,
                )

        return Response(
            {
                "bookmark": existing_bookmark_data,
                "metadata": metadata.to_dict(),
                "auto_tags": auto_tags,
            },
            status=status.HTTP_200_OK,
        )


class TagViewSet(
    viewsets.GenericViewSet,
    mixins.ListModelMixin,
    mixins.RetrieveModelMixin,
    mixins.CreateModelMixin,
):
    serializer_class = TagSerializer

    def get_queryset(self):
        user = self.request.user
        return Tag.objects.all().filter(owner=user)

    def get_serializer_context(self):
        return {"user": self.request.user}


class UserViewSet(viewsets.GenericViewSet):
    @action(methods=["get"], detail=False)
    def profile(self, request):
        return Response(UserProfileSerializer(request.user.profile).data)


router = DefaultRouter()
router.register(r"bookmarks", BookmarkViewSet, basename="bookmark")
router.register(r"tags", TagViewSet, basename="tag")
router.register(r"user", UserViewSet, basename="user")

bookmarks/views/assets.py
import gzip
import os

from django.conf import settings
from django.http import (
    HttpResponse,
    Http404,
)
from django.shortcuts import render

from bookmarks.models import BookmarkAsset


def _access_asset(request, asset_id: int):
    try:
        asset = BookmarkAsset.objects.get(pk=asset_id)
    except BookmarkAsset.DoesNotExist:
        raise Http404("Asset does not exist")

    bookmark = asset.bookmark
    is_owner = bookmark.owner == request.user
    is_shared = (
        request.user.is_authenticated
        and bookmark.shared
        and bookmark.owner.profile.enable_sharing
    )
    is_public_shared = bookmark.shared and bookmark.owner.profile.enable_public_sharing

    if not is_owner and not is_shared and not is_public_shared:
        raise Http404("Bookmark does not exist")

    return asset


def _get_asset_content(asset):
    filepath = os.path.join(settings.LD_ASSET_FOLDER, asset.file)

    if not os.path.exists(filepath):
        raise Http404("Asset file does not exist")

    if asset.gzip:
        with gzip.open(filepath, "rb") as f:
            content = f.read()
    else:
        with open(filepath, "rb") as f:
            content = f.read()

    return content


def view(request, asset_id: int):
    asset = _access_asset(request, asset_id)
    content = _get_asset_content(asset)

    return HttpResponse(content, content_type=asset.content_type)


def read(request, asset_id: int):
    asset = _access_asset(request, asset_id)
    content = _get_asset_content(asset)
    content = content.decode("utf-8")

    return render(
        request,
        "bookmarks/read.html",
        {
            "content": content,
        },
    )

bookmarks/views/health.py
from django.db import connections
from django.http import JsonResponse

from bookmarks.views.settings import app_version


def health(request):
    code = 200
    response = {"version": app_version, "status": "healthy"}

    try:
        connections["default"].ensure_connection()
    except Exception:
        response["status"] = "unhealthy"
        code = 500

    return JsonResponse(response, status=code)

bookmarks/views/manifest.py
from django.http import JsonResponse
from django.conf import settings


def manifest(request):
    response = {
        "short_name": "linkding",
        "name": "linkding",
        "description": "Self-hosted bookmark service",
        "start_url": "bookmarks",
        "display": "standalone",
        "scope": "/" + settings.LD_CONTEXT_PATH,
        "theme_color": "#5856e0",
        "background_color": (
            "#161822" if request.user_profile.theme == "dark" else "#ffffff"
        ),
        "icons": [
            {
                "src": "/" + settings.LD_CONTEXT_PATH + "static/logo.svg",
                "type": "image/svg+xml",
                "sizes": "512x512",
                "purpose": "any",
            },
            {
                "src": "/" + settings.LD_CONTEXT_PATH + "static/logo-512.png",
                "type": "image/png",
                "sizes": "512x512",
                "purpose": "any",
            },
            {
                "src": "/" + settings.LD_CONTEXT_PATH + "static/logo-192.png",
                "type": "image/png",
                "sizes": "192x192",
                "purpose": "any",
            },
            {
                "src": "/" + settings.LD_CONTEXT_PATH + "static/maskable-logo.svg",
                "type": "image/svg+xml",
                "sizes": "512x512",
                "purpose": "maskable",
            },
            {
                "src": "/" + settings.LD_CONTEXT_PATH + "static/maskable-logo-512.png",
                "type": "image/png",
                "sizes": "512x512",
                "purpose": "maskable",
            },
            {
                "src": "/" + settings.LD_CONTEXT_PATH + "static/maskable-logo-192.png",
                "type": "image/png",
                "sizes": "192x192",
                "purpose": "maskable",
            },
        ],
        "shortcuts": [
            {
                "name": "Add bookmark",
                "url": "/" + settings.LD_CONTEXT_PATH + "bookmarks/new",
            },
            {
                "name": "Archived",
                "url": "/" + settings.LD_CONTEXT_PATH + "bookmarks/archived",
            },
            {
                "name": "Unread",
                "url": "/" + settings.LD_CONTEXT_PATH + "bookmarks?unread=yes",
            },
            {
                "name": "Untagged",
                "url": "/" + settings.LD_CONTEXT_PATH + "bookmarks?q=!untagged",
            },
            {
                "name": "Shared",
                "url": "/" + settings.LD_CONTEXT_PATH + "bookmarks/shared",
            },
        ],
        "screenshots": [
            {
                "src": "/"
                + settings.LD_CONTEXT_PATH
                + "static/linkding-screenshot.png",
                "type": "image/png",
                "sizes": "2158x1160",
                "form_factor": "wide",
            }
        ],
        "share_target": {
            "action": "/" + settings.LD_CONTEXT_PATH + "bookmarks/new",
            "method": "GET",
            "enctype": "application/x-www-form-urlencoded",
            "params": {
                "url": "url",
                "text": "url",
                "title": "title",
            },
        },
    }

    return JsonResponse(response, status=200)

bookmarks/views/partials.py
from bookmarks.views import contexts, turbo


def render_bookmark_update(request, bookmark_list, tag_cloud, details):
    return turbo.stream(
        request,
        "bookmarks/updates/bookmark_view_stream.html",
        {
            "bookmark_list": bookmark_list,
            "tag_cloud": tag_cloud,
            "details": details,
        },
    )


def active_bookmark_update(request):
    bookmark_list = contexts.ActiveBookmarkListContext(request)
    tag_cloud = contexts.ActiveTagCloudContext(request)
    details = contexts.get_details_context(
        request, contexts.ActiveBookmarkDetailsContext
    )
    return render_bookmark_update(request, bookmark_list, tag_cloud, details)


def archived_bookmark_update(request):
    bookmark_list = contexts.ArchivedBookmarkListContext(request)
    tag_cloud = contexts.ArchivedTagCloudContext(request)
    details = contexts.get_details_context(
        request, contexts.ArchivedBookmarkDetailsContext
    )
    return render_bookmark_update(request, bookmark_list, tag_cloud, details)


def shared_bookmark_update(request):
    bookmark_list = contexts.SharedBookmarkListContext(request)
    tag_cloud = contexts.SharedTagCloudContext(request)
    details = contexts.get_details_context(
        request, contexts.SharedBookmarkDetailsContext
    )
    return render_bookmark_update(request, bookmark_list, tag_cloud, details)

bookmarks/views/root.py
from django.http import HttpResponseRedirect
from django.urls import reverse

from bookmarks.models import GlobalSettings


def root(request):
    # Redirect unauthenticated users to the configured landing page
    if not request.user.is_authenticated:
        settings = request.global_settings

        if settings.landing_page == GlobalSettings.LANDING_PAGE_SHARED_BOOKMARKS:
            return HttpResponseRedirect(reverse("bookmarks:shared"))
        else:
            return HttpResponseRedirect(reverse("login"))

    # Redirect authenticated users to the bookmarks page
    return HttpResponseRedirect(reverse("bookmarks:index"))

bookmarks/templates/bookmarks/archive.html
{% extends "bookmarks/layout.html" %}
{% load static %}
{% load shared %}
{% load bookmarks %}

{% block content %}
  <div ld-bulk-edit class="bookmarks-page grid columns-md-1">

    {# Bookmark list #}
    <section class="content-area col-2">
      <div class="content-area-header mb-0">
        <h2>Archived bookmarks</h2>
        <div class="header-controls">
          {% bookmark_search bookmark_list.search mode='archived' %}
          {% include 'bookmarks/bulk_edit/toggle.html' %}
          <button ld-tag-modal class="btn ml-2 show-md">Tags
          </button>
        </div>
      </div>

      <form class="bookmark-actions"
            action="{{ bookmark_list.action_url|safe }}"
            method="post" autocomplete="off">
        {% csrf_token %}
        {% include 'bookmarks/bulk_edit/bar.html' with disable_actions='bulk_archive' %}

        <div id="bookmark-list-container">
          {% include 'bookmarks/bookmark_list.html' %}
        </div>
      </form>
    </section>

    {# Tag cloud #}
    <section class="content-area col-1 hide-md">
      <div class="content-area-header">
        <h2>Tags</h2>
      </div>
      <div id="tag-cloud-container">
        {% include 'bookmarks/tag_cloud.html' %}
      </div>
    </section>

    {# Bookmark details #}
    <turbo-frame id="details-modal" target="_top">
      {% if details %}
        {% include 'bookmarks/details/modal.html' %}
      {% endif %}
    </turbo-frame>
  </div>
{% endblock %}

bookmarks/templates/bookmarks/close.html
{% extends "bookmarks/layout.html" %}

{% block content %}
  <script type="application/javascript">
    window.close()
  </script>
  <p>You can now close this window.</p>
{% endblock %}

bookmarks/templates/bookmarks/edit.html
{% extends 'bookmarks/layout.html' %}
{% load bookmarks %}

{% block content %}
  <div class="bookmarks-form-page">
    <section class="content-area">
      <div class="content-area-header">
        <h2>Edit bookmark</h2>
      </div>
      <form action="{% url 'bookmarks:edit' bookmark_id %}?return_url={{ return_url|urlencode }}" method="post"
            novalidate>
        {% bookmark_form form return_url bookmark_id %}
      </form>
    </section>
  </div>
{% endblock %}

bookmarks/templates/bookmarks/empty_bookmarks.html
<div class="empty">
  <p class="empty-title h5">You have no bookmarks yet</p>
  <p class="empty-subtitle">
    You can get started by <a href="{% url 'bookmarks:new' %}">adding</a> bookmarks,
    <a href="{% url 'bookmarks:settings.general' %}">importing</a> your existing bookmarks or configuring the
    <a href="{% url 'bookmarks:settings.integrations' %}">browser extension</a> or the <a
      href="{% url 'bookmarks:settings.integrations' %}">bookmarklet</a>.
  </p>
</div>

bookmarks/templates/bookmarks/head.html
{% load static %}

<head>
  <meta charset="UTF-8">
  <link rel="icon" href="{% static 'favicon.ico' %}" sizes="48x48">
  <link rel="icon" href="{% static 'favicon.svg' %}" sizes="any" type="image/svg+xml">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
  <link rel="mask-icon" href="{% static 'safari-pinned-tab.svg' %}" color="#5856e0">
  <link rel="manifest" href="{% url 'bookmarks:manifest' %}">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimal-ui">
  <meta name="description" content="Self-hosted bookmark service">
  <meta name="robots" content="index,follow">
  <meta name="author" content="Sascha Ißbrücker">
  <title>linkding</title>
  {# Include specific theme variant based on user profile setting #}
  {% if request.user_profile.theme == 'light' %}
    <link href="{% static 'theme-light.css' %}?v={{ app_version }}" rel="stylesheet" type="text/css"/>
    <meta name="theme-color" content="#5856e0">
  {% elif request.user_profile.theme == 'dark' %}
    <link href="{% static 'theme-dark.css' %}?v={{ app_version }}" rel="stylesheet" type="text/css"/>
    <meta name="theme-color" content="#161822">
  {% else %}
    {# Use auto theme as fallback #}
    <link href="{% static 'theme-dark.css' %}?v={{ app_version }}" rel="stylesheet" type="text/css"
          media="(prefers-color-scheme: dark)"/>
    <link href="{% static 'theme-light.css' %}?v={{ app_version }}" rel="stylesheet" type="text/css"
          media="(prefers-color-scheme: light)"/>
    <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#161822">
    <meta name="theme-color" media="(prefers-color-scheme: light)" content="#5856e0">
  {% endif %}
  {% if request.user_profile.custom_css %}
    <style>{{ request.user_profile.custom_css }}</style>
  {% endif %}
  <meta name="turbo-cache-control" content="no-preview">
  {% if not request.global_settings.enable_link_prefetch %}
    <meta name="turbo-prefetch" content="false">
  {% endif %}
  <script src="{% static "bundle.js" %}?v={{ app_version }}"></script>
</head>

bookmarks/templates/bookmarks/index.html
{% extends "bookmarks/layout.html" %}
{% load static %}
{% load shared %}
{% load bookmarks %}

{% block content %}
  <div ld-bulk-edit class="bookmarks-page grid columns-md-1">

    {# Bookmark list #}
    <section class="content-area col-2">
      <div class="content-area-header mb-0">
        <h2>Bookmarks</h2>
        <div class="header-controls">
          {% bookmark_search bookmark_list.search %}
          {% include 'bookmarks/bulk_edit/toggle.html' %}
          <button ld-tag-modal class="btn ml-2 show-md">Tags</button>
        </div>
      </div>

      <form class="bookmark-actions"
            action="{{ bookmark_list.action_url|safe }}"
            method="post" autocomplete="off">
        {% csrf_token %}
        {% include 'bookmarks/bulk_edit/bar.html' with disable_actions='bulk_unarchive' %}

        <div id="bookmark-list-container">
          {% include 'bookmarks/bookmark_list.html' %}
        </div>
      </form>
    </section>

    {# Tag cloud #}
    <section class="content-area col-1 hide-md">
      <div class="content-area-header">
        <h2>Tags</h2>
      </div>
      <div id="tag-cloud-container">
        {% include 'bookmarks/tag_cloud.html' %}
      </div>
    </section>

    {# Bookmark details #}
    <turbo-frame id="details-modal" target="_top">
      {% if details %}
        {% include 'bookmarks/details/modal.html' %}
      {% endif %}
    </turbo-frame>
  </div>
{% endblock %}

bookmarks/templates/bookmarks/nav_menu.html
{% load shared %}
{% htmlmin %}
  {# Basic menu list #}
  <div class="hide-md">
    <a href="{% url 'bookmarks:new' %}" class="btn btn-primary mr-2">Add bookmark</a>
    <div class="dropdown">
      <button class="btn btn-link dropdown-toggle" tabindex="0">
        Bookmarks
      </button>
      <ul class="menu">
        <li class="menu-item">
          <a href="{% url 'bookmarks:index' %}" class="menu-link">Active</a>
        </li>
        <li class="menu-item">
          <a href="{% url 'bookmarks:archived' %}" class="menu-link">Archived</a>
        </li>
        {% if request.user_profile.enable_sharing %}
          <li class="menu-item">
            <a href="{% url 'bookmarks:shared' %}" class="menu-link">Shared</a>
          </li>
        {% endif %}
        <li class="menu-item">
          <a href="{% url 'bookmarks:index' %}?unread=yes" class="menu-link">Unread</a>
        </li>
        <li class="menu-item">
          <a href="{% url 'bookmarks:index' %}?q=!untagged" class="menu-link">Untagged</a>
        </li>
      </ul>
    </div>
    <a href="{% url 'bookmarks:settings.index' %}" class="btn btn-link">Settings</a>
    <form class="d-inline" action="{% url 'logout' %}" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-link">Logout</button>
    </form>
  </div>
  {# Menu drop-down for smaller devices #}
  <div class="show-md">
    <a href="{% url 'bookmarks:new' %}" class="btn btn-primary">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"
           style="width: 24px; height: 24px">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
      </svg>
    </a>
    <div ld-dropdown class="dropdown dropdown-right">
      <button class="btn btn-link dropdown-toggle" tabindex="0">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"
             style="width: 24px; height: 24px">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
        </svg>
      </button>
      <!-- menu component -->
      <ul class="menu">
        <li class="menu-item">
          <a href="{% url 'bookmarks:index' %}" class="menu-link">Bookmarks</a>
        </li>
        <li class="menu-item">
          <a href="{% url 'bookmarks:archived' %}" class="menu-link">Archived</a>
        </li>
        {% if request.user_profile.enable_sharing %}
          <li class="menu-item">
            <a href="{% url 'bookmarks:shared' %}" class="menu-link">Shared</a>
          </li>
        {% endif %}
        <li class="menu-item">
          <a href="{% url 'bookmarks:index' %}?unread=yes" class="menu-link">Unread</a>
        </li>
        <li class="menu-item">
          <a href="{% url 'bookmarks:index' %}?q=!untagged" class="menu-link">Untagged</a>
        </li>
        <div class="divider"></div>
        <li class="menu-item">
          <a href="{% url 'bookmarks:settings.index' %}" class="menu-link">Settings</a>
        </li>
        <li class="menu-item">
          <form class="d-inline" action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-link menu-link">Logout</button>
          </form>
        </li>
      </ul>
    </div>
  </div>
{% endhtmlmin %}

bookmarks/templates/bookmarks/new.html
{% extends 'bookmarks/layout.html' %}
{% load bookmarks %}

{% block content %}
  <div class="bookmarks-form-page">
    <section class="content-area">
      <div class="content-area-header">
        <h2>New bookmark</h2>
      </div>
      <form action="{% url 'bookmarks:new' %}" method="post" novalidate>
        {% bookmark_form form return_url auto_close=auto_close %}
      </form>
    </section>
  </div>
{% endblock %}

bookmarks/templates/bookmarks/user_select.html
{% load widget_tweaks %}

<form id="user-select" action="" method="get">
  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}
  <div class="form-group">
    <div class="d-flex">
      {% render_field form.user class+="form-select" ld-auto-submit="" %}
      <noscript>
        <button type="submit" class="btn btn-link ml-2">Apply</button>
      </noscript>
    </div>
  </div>
</form>